$schema: ../../../schema/mcp-agent.config.schema.json

execution_engine: asyncio
logger:
  transports: [console, file]
  level: info
  show_progress: true
  path: "logs/instagram_gift_advisor.jsonl"
  path_settings:
    path_pattern: "logs/instagram_gift_advisor_{unique_id}.jsonl"
    unique_id: "timestamp"
    timestamp_format: "%Y%m%d_%H%M%S"
  filters:
    - logger: "root"
      level: error

mcp:
  servers:
    #    Specify the apify server in mcp_agent.secrets.yaml since it contains your API token in the URL
    #    apify:
    #      command: "npx"
    #      args:
    #        [
    #         "mcp-remote",
    #         "https://mcp.apify.com/sse?token=${APIFY_API_TOKEN}&actors=apify/instagram-api-scraper",
    #        ]
    fetch:
      command: "uvx"
      args: ["mcp-server-fetch"]
    g-search:
      command: "npx"
      args: ["-y", "g-search-mcp"]

openai:
  # Secrets (API keys, etc.) are stored in an mcp_agent.secrets.yaml file which can be gitignored
  default_model: "gpt-4o-mini"
anthropic:
  default_model: claude-sonnet-4-20250514
