# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create working directory
WORKDIR /app

# Copy package files and install dependencies without running scripts
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy TypeScript configuration and source code
COPY tsconfig.json ./
COPY src ./src

# Build the project
RUN npm run build

# Expose port if needed

# Run the MCP server
ENTRYPOINT ["node", "dist/index.js"]
